CREATE TABLE `comschoolmand`.`results` (
    `resId` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `studId` VARCHAR(30) NOT NULL,
    `studName` VARCHAR(30) NOT NULL,
    `acadYr` VARCHAR(30) NOT NULL,
    `term` VARCHAR(30) NOT NULL,
    `resClass` VARCHAR(20) NOT NULL,
    `arm` VARCHAR(20) NOT NULL,
    `combination` VARCHAR(20) NOT NULL,
    `ca1` INT(11) NOT NULL,
    `ca2` INT(11) NULL,
    `exam` INT(11) NULL,
    `examTotal` INT(11) NULL,
    `chm` INT(11) NULL,
    `clm` INT(11) NULL,
    `cam` INT(11) NULL,
    ) ENGINE = InnoDB;